name: Docs
on:
  push:
    branches:
      - main
    paths:
      - src/index.ts
      - src/EVMcrispr.ts
      - src/errors.ts
      - src/types.ts
      - README.md
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn add typedoc
          yarn generate-docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
